name: Build App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'
    
    # Step 3: Install dependencies
    - name: Install Dependencies
      working-directory: ./client
      run: npm install

    # Step 4: Build the client
    - name: Build Client
      working-directory: ./client
      run: npm run build