name: Deploy Client to Vercel

on:
  workflow_dispatch:  # Allows manual trigger
    branches:
      - main
      - feat/21_deploy_frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
     # Step 1: Trigger the client build workflow manually (use the existing client-build.yml)
    - name: Trigger client build workflow
      uses: peter-evans/workflow-dispatch@v1
      with:
        repository: ${{ github.repository }}  # Current repository
        workflow: client-build.yml  # The name of the build workflow
        ref: ${{ github.ref }}  # Use the current branch for the build

    - uses: actions/checkout@v4

    # Install Vercel CLI
    - name: Install Vercel CLI
      run: npm install -g vercel

    # Authenticate with Vercel (using GitHub secrets for secure deployment)
    - name: Vercel Authentication
      run: vercel login ${{ secrets.VERCEL_TOKEN }} --token
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    # Deploy to Vercel
    - name: Deploy to Vercel
      run: |
        vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
      working-directory: ./client
