# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Client App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'

    # Install dependencies in the 'client' directory (or 'API' depending on your structure)
    - name: Install Dependencies (Client)
      run: npm ci
      working-directory: ./client 

    # Build the client app (or API) in the 'client' directory
    - name: Build Client
      run: npm run build --if-present
      working-directory: ./client

    # Optionally, run tests (if applicable) in the 'client' directory
    # - run: npm test
    #   working-directory: ./client